### ISSUE TITLE
关于评论系统Gitalk的问题

### ISSUE THREAD

**Issue by monkeyip** [Molunerfinn/Molunerfinn.github.io#105]
我按照文档把主题文件设置好了。
gitalk:
  enable: true
  client_id: 你的client id 
  client_secret: 你的client secret
  repo: 你的github仓库
  owner: 你的github用户名
  admin: 该仓库的拥有者或协作者

但是gitalk里说到：
## npm 安装
npm i --save gitalk
import 'gitalk/dist/gitalk.css'     --这两个import命令，该在哪个环境下执行呢？
import Gitalk from 'gitalk'

### 添加一个容器：

<div id="gitalk-container"></div>
用下面的 Javascript 代码来生成 gitalk 插件：

var gitalk = new Gitalk({
  clientID: 'GitHub Application Client ID',
  clientSecret: 'GitHub Application Client Secret',
  repo: 'GitHub repo',
  owner: 'GitHub repo owner',
  admin: ['GitHub repo owner and collaborators, only these guys can initialize github issues'],
  id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: false  // Facebook-like distraction free mode
})

gitalk.render('gitalk-container')

*这些代码，我该在哪里修改呢？*

**Comment by Molunerfinn** [comment]
这些代码你都不用写，melody会自动帮你生成

**Comment by Molunerfinn** [comment]
换句话说，hexo-theme-melody里，你只需要关注你的配置文件，其他跟DOM有关的东西你都不用关心，配置好配置文件就能使用
