### ISSUE TITLE
eeeee

### ISSUE THREAD

**Issue by Xanadu-zxl** [Molunerfinn/Molunerfinn.github.io#114]
不好意思，看了你的于洛阳的文章过来了，就像遇到知音却又 不知怎么开口，做一个男人太矫情了 哈哈哈   又看了几篇文章只想说 老铁🐂🍺

**Comment by Molunerfinn** [comment]
感谢支持，那个时候比较年轻哈

**Comment by Xanadu-zxl** [comment]
过去的一切塑造了现在的我们嘛，刚毕业也是前端方向_向大佬看齐
